---
os: osx

language: ruby

before_script:
  - /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
  - brew tap leominov/tap

script:
  - brew install yucca
  - yucca version
